name: dash_validator
description: A Dart validation library to simplify the use of validation, and used to validate fields and other things
version: 1.0.1
homepage: https://github.com/MateusHBR/dash_validator

environment:
  sdk: '>=2.14.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
